interface Resources {
  "home": {
    "started": "Get started by editing",
    "by": "By ",
    "docs": {
      "title": "Docs ",
      "description": "Find in-depth information about Next.js features and API."
    },
    "learn": {
      "title": "Learn ",
      "description": "Learn about Next.js in an interactive course with quizzes!"
    },
    "templates": {
      "title": "Templates ",
      "description": "Explore starter templates for Next.js."
    },
    "deploy": {
      "title": "Deploy ",
      "description": "Instantly deploy your Next.js site to a shareable URL with Vercel."
    }
  },
  "meta": {
    "home": {
      "title": "Create Next App",
      "description": "Generated by create next app",
      "keywords": [
        "My keyword1",
        "My keyword2",
        "My keyword3"
      ],
      "authors": {
        "name": "My name",
        "url": "https://www.my-url.com"
      },
      "creator": "@MyName",
      "icons": {
        "icon": "/favicon.ico",
        "shortcut": "/assets/favicon-16x16.png",
        "apple": "/assets/apple.png"
      },
      "images": [
        "/assets/og.jpg"
      ],
      "locale": "en-US"
    }
  }
}

export default Resources;
